version: "3.0"
services:
  limesurvey:
    build:
      # Hint: Change it to 3.0/apache/ if you want to use LimeSurvey 3.*
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - abs-surveys:/var/www/html/upload/surveys
    networks:
      - proxy
      - lime-network
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=/run/secrets/db_password"
      - "ADMIN_PASSWORD=/run/secrets/admin_password"
    secrets:
      - db_password
      - admin_password
  lime-db:
    image: docker.io/postgres:10
    volumes:
      - abs-db:/var/lib/postgresql/data
    networks:
      - lime-network
    environment:
      - "POSTGRES_USER=limesurvey"
      - "POSTGRES_DB=limesurvey"
      - "POSTGRES_PASSWORD=/run/secrets/db_password"
    secrets:
      - db_password
      - db_root_password
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    networks:
      - lime-network
    volumes:
      - /mnt/abs-backup:/backups
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - POSTGRES_HOST=lime-db
      - POSTGRES_DB=limesurvey
      - POSTGRES_USER=limesurvey
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    secrets:
      - db_password
      - db_root_password
volumes:
  abs-db:
  abs-surveys:
networks:
  proxy:
    name: proxy
    external: true
  lime-network:

  
secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  admin_password:
    file: admin_password.txt
