version: "3.0"
services:
  limesurvey:
    build:
      # Hint: Change it to 3.0/apache/ if you want to use LimeSurvey 3.*
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - abs-surveys:/var/www/html/upload/surveys
    networks:
      - lan
      - lime-network
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=$POSTGRES_PORT"
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=$POSTGRES_PASSWORD"
      - "ADMIN_PASSWORD=$ADMIN_PASSWORD"
  lime-db:
    image: docker.io/postgres:10
    volumes:
      - abs-db:/var/lib/postgresql/data
    networks:
      - lime-network
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_DB=$POSTGRES_DB"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    networks:
      - lime-network
    volumes:
      - abs-backup:/backups
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - POSTGRES_HOST=lime-db
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
volumes:
  abs-db:
  abs-surveys:
  abs-backup:
    external: true
networks:
  lan:
    name: lan-network
    external: true
  lime-network:
