version: "3.0"
services:
  limesurvey:
    build:
      # Hint: Change it to 3.0/apache/ if you want to use LimeSurvey 3.*
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - abs-surveys:/var/www/html/upload/surveys
    networks:
      - lime-network
      - proxy
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      - "DB_TYPE=mysql"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "DB_PASSWORD=/run/secrets/db_password"
      - "ADMIN_PASSWORD=/run/secrets/admin_password"
    secrets:
      - db_password
      - admin_password
  mariadb:
    image: mariadb
    environment:
      - "MARIADB_DATABASE=limesurvey"
      - "MARIADB_USER=limesurvey"
      - MARIADB_PASSWORD=/run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    networks:
      - lime-network
volumes:
  abs-db:
  abs-surveys:
networks:
  proxy:
    external: true
  lime-network:

secrets:
  db_password:
    file: db_password.txt
  admin_password:
    file: admin_password.txt
